### ISSUE TITLE
Swift 5.1 compilation error

### ISSUE THREAD

**Issue by Davidde94** [amzn/smoke-http#83]
See attached build log when running `swift test`:

```
[687/719] Compiling SmokeHTTPClient MockCoreInvocationReporting.swift
/workspace/.logs/**/*.log/0CD98C14-3F23-427E-BBF8-7BB9B9327D6D/repos/smoke-http/Sources/SmokeHTTPClient/MockCoreInvocationReporting.swift:33:5: error: return from initializer without initializing all stored properties
    }
    ^
/workspace/.logs/**/*.log/0CD98C14-3F23-427E-BBF8-7BB9B9327D6D/repos/smoke-http/Sources/SmokeHTTPClient/StandardHTTPClientCoreInvocationReporting.swift:28:16: note: 'self.eventLoop' not initialized
    public var eventLoop: EventLoop?
               ^
/workspace/.logs/**/*.log/0CD98C14-3F23-427E-BBF8-7BB9B9327D6D/repos/smoke-http/Sources/SmokeHTTPClient/StandardHTTPClientCoreInvocationReporting.swift:29:16: note: 'self.outwardsRequestAggregator' not initialized
    public var outwardsRequestAggregator: OutwardsRequestAggregator?
               ^
[688/719] Compiling SmokeHTTPClient HTTPRequestInputProtocol.swift
```

It's possible this is a compiler error, but thought we should bring it to your attention. As 5.1 is quite old at this point (relatively), is it possible to just kill support?

**Comment by tachyonics** [comment]
Thanks David, according to our support schedule[1], support for 5.1 will be dropped after the 12th so very soon this will stop being an issue. However code-style-wise, I think it is worth fixing the constructor to delegate to the primary constructor to ensure this mis-match doesn't happen again. I have created a pull request to make this change; let me know if you have any concerns with this change.

Also we have a compilation against 5.1[2] in our CI test suite. Do you know if there is any reason this issue isn't showing up there?

[1] https://github.com/amzn/smoke-aws/blob/main/docs/Support_Policy.md
[2] https://travis-ci.com/github/amzn/smoke-http/jobs/503249129

**Comment by Davidde94** [comment]
Yeh, it's very strange. As the values are optional they shouldn't need a default value anyway? We use `swift:5.1` in our pipeline, which I think is based on Ubuntu 18.04 also, so I have no plausible explanation...

**Comment by tachyonics** [comment]
Resolving as Swift 5.1 is no longer supported.
