### ISSUE TITLE
Import NIOFoundationCompat where it's used

### ISSUE THREAD

**Issue by Lukasa** [amzn/smoke-http#93]
smoke-http uses at least one method defined in NIOFoundationCompat:

https://github.com/amzn/smoke-http/blob/95e473c7db33ca6b4e805245c0cf14580a302a3c/Sources/SmokeHTTPClient/HTTPOperationsClient.swift#L287

But that file does not import NIOFoundationCompat. As a result, recent Swift builds trip over the method and don't handle it well. The file should import NIOFoundationCompat.

**Comment by tachyonics** [comment]
Closing as a fix for this has been merged.
